### ISSUE TITLE
请教一下我编好的固件在国内无法下载，而您的可以下载，是怎么做到的？

### ISSUE THREAD

**Issue by kentmay** [RealKiro/Actions-OpenWrt#1]
刚才发现我可以下载您编的竞斗云固件。谢谢了。

**Comment by RealKiro** [comment]
你的梯子不行，建议在非高峰期（早上）下载，或者换梯子

**Comment by kentmay** [comment]
哦，谢谢回复~，有可以推荐的梯子吗 ：）

**Comment by RealKiro** [comment]
> 哦，谢谢回复~，有可以推荐的梯子吗 ：）

http://tinyurl.com/txgrjob
邮箱注册送10G流量
