### ISSUE TITLE
重启后配置被重置是啥情况，哥们有遇到么？

### ISSUE THREAD

**Issue by A-GG** [RealKiro/Actions-OpenWrt#3]
找了好多固件，自己也编译了好几个，但是都有俩问题：
1. 重启或者断电后配置被重置
2. shadowsocksr plus+ 服务总是莫名其妙的停掉

哥们如果有遇到解决了，辛苦给出出主意，如果没解决我们一起研究

**Comment by RealKiro** [comment]
你怕是刷错了固件，刷成了kernel
![image](https://user-images.githubusercontent.com/33367701/76824410-f927db80-6851-11ea-9bf2-799b368b2248.png)

**Comment by finish8** [comment]
https://github.com/finish8/openwrt-wt3200-firmware

**Comment by RealKiro** [comment]
> https://github.com/finish8/openwrt-wt3200-firmware
> 
> 我用的是这个固件，如果有空的话，您帮忙看看是啥问题
> 
> 刚看了一下，感觉你说到点子上了。。。
> 我这最终编译出来的文件名是这个，不是啥factory之类的
> openwrt-ramips-mt7620-phicomm_psg1218a-initramfs-kernel.bin

没编译出来，包太大

**Comment by finish8** [comment]
我这几天研究了一下，你帮我看看我说的对不对啊

**Comment by RealKiro** [comment]
> ## `疑惑`
> 还看到有网友，说可以修改 `/targets/linux/xxxx/image/xxxx.mk`中的 `IMAGE_SIZE` 来设置最终生成的包的类型，但是这个东西不是设备本身决定的么？还能修改？不会出问题吗？

那是x86_64用的，你不改硬件不要xjb乱改config

**Comment by finish8** [comment]
关键是 `config` 里啥 `package` 都不加，大小都能超....
有啥办法可以在 `config` 里移除一些他默认的包不？

**Comment by RealKiro** [comment]
> 关键是 `config` 里啥 `package` 都不加，大小都能超....
> 有啥办法可以在 `config` 里移除一些他默认的包不？

make menuconfig 请

**Comment by A-GG** [comment]
我放弃了，K2闪存太小，带宽也不够，用树莓派弄了个旁路由玩，不折腾了。
